default:
  # Вказує на кореневу директорію проєкту
  root_dir: "."
  # Директорія, де зберігаються конфігураційні файли
  config_dir: "config"
  # Директорія для інших YAML конфігурацій (ми тримаємо їх тут же)
  yaml_dir: "config"
  # Директорія для медіа-файлів (зображення)
  media_dir: "media"
  # Директорія для бази даних
  db_dir: "db"